apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    infra.levizitting.com/health-gate: "true"
spec:
  project: platform
  source:
    repoURL: ssh://git@github.com/glitchedmob/infra-k8s-apps.git
    path: src/k8s/platform/services/crowdsec
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: crowdsec
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
