apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-oidc
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
    infra.levizitting.com/health-gate: "true"
    infra.levizitting.com/issuer-operation-gate: "true"
    infra.levizitting.com/issuer-input-fingerprint: "b1bf362ff001b1eec0233bd2cc3aa7dee5c37631"
spec:
  project: platform
  source:
    repoURL: ssh://git@github.com/glitchedmob/infra-k8s-apps.git
    path: src/k8s/platform/services/k8s-oidc
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-oidc
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /spec/duration
        - /spec/renewBefore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
