apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-runtime
  namespace: authentik
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: authentik-runtime
  data:
    - secretKey: bootstrapToken
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/authentik/bootstrap-token
    - secretKey: secretKey
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/authentik/secret-key
    - secretKey: smtpUsername
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/authentik/ses/username
    - secretKey: smtpPassword
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/authentik/ses/password
