apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-backup-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: k8up-b2-credentials
    creationPolicy: Owner
  data:
    - secretKey: account-id
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/backups/b2-account-id
    - secretKey: account-key
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/backups/b2-account-key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-k8up-repo-password
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: authentik-k8up-repo-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/backups/authentik/restic-password
