apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - traefik-helmchartconfig.yaml
  - middleware-client-headers.yaml
  - cloudflared-token.yaml
  - traefik-tailnet-auth.yaml
  - traefik-ingress-policy.yaml
  - middleware-crowdsec.yaml
  - middleware-crowdsec-header.yaml
  - externalsecret-crowdsec.yaml
  - traefik-dashboard-ingress
