apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - valkey-operator.yaml
  - cnpg.yaml
  - external-secrets.yaml
  - cert-manager.yaml
  - argocd-config.yaml
  - bootstrap-config.yaml
  - openbao.yaml
  - argocd-ingress.yaml
  - apps.yaml
