apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oauth2-proxy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - chart: oauth2-proxy
      repoURL: https://oauth2-proxy.github.io/manifests
      targetRevision: 7.x.*
      helm:
        values: |
          podAnnotations:
            reloader.stakater.com/auto: "true"

          config: {}

          extraEnv:
            - name: OAUTH2_PROXY_CLIENT_ID
              value: oauth2-proxy
            - name: OAUTH2_PROXY_PROVIDER
              value: oidc
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              value: https://sso.levizitting.com
            - name: OAUTH2_PROXY_REDIRECT_URL
              value: https://auth.levizitting.com/oauth2/callback
            - name: OAUTH2_PROXY_COOKIE_DOMAIN
              value: ".levizitting.com"
            - name: OAUTH2_PROXY_UPSTREAMS
              value: static://200
            - name: OAUTH2_PROXY_SET_AUTHORIZATION_HEADER
              value: "true"
            - name: OAUTH2_PROXY_ALLOWED_USERS
              value: "glitchedmob"
            - name: OAUTH2_PROXY_WHITELIST_REDIRECT_DOMAINS
              value: ".levizitting.com"
            - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
              value: "true"
            - name: OAUTH2_PROXY_SSL_INSECURE_SKIP_VERIFY
              value: "true"

          extraEnvFrom:
            - secretRef:
                name: dex-oauth2-proxy-secrets

          ingress:
            enabled: false

          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
    - repoURL: ssh://git@github.com/glitchedmob/infra-k8s-apps.git
      path: src/k8s/oauth2-proxy
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: oauth2-proxy
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /spec/duration
        - /spec/renewBefore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
