apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mcphub
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: mcphub-mcphub-https-redirect@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - mcp.levizitting.com
      secretName: mcp-levizitting-com-tls
  rules:
    - host: mcp.levizitting.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mcphub
                port:
                  name: http
