apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-grafana-client-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: dex-grafana-client-secret
  data:
    - secretKey: GF_OAUTH_CLIENT_SECRET
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/dex-client-grafana-secret
