apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-prometheus-stack.yaml
  - dex-grafana-client-secret.yaml
  - loki.yaml
  - tempo.yaml
  - otel-operator.yaml
  - alloy.yaml
  - grafana-ingress.yaml
