apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-server-env
  namespace: infisical
spec:
  refreshInterval: 1h
  target:
    name: infisical-server-env
    creationPolicy: Owner
    template:
      data:
        ENCRYPTION_KEY: "{{ .encryptionKey }}"
        AUTH_SECRET: "{{ .authSecret }}"
        REDIS_URL: "redis://:{{ .redisPassword }}@infisical-redis.infisical-redis:6379"
  data:
    - secretKey: encryptionKey
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/infisical-encryption-key
      sourceRef:
        storeRef:
          name: aws-ssm
          kind: ClusterSecretStore
    - secretKey: authSecret
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/infisical-auth-secret
      sourceRef:
        storeRef:
          name: aws-ssm
          kind: ClusterSecretStore
    - secretKey: redisPassword
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/infisical-redis-password
      sourceRef:
        storeRef:
          name: aws-ssm
          kind: ClusterSecretStore
