apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-oauth2-proxy-secrets
  namespace: oauth2-proxy
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: oauth2-proxy
    template:
      mergePolicy: Merge
      data:
        client-id: oauth2-proxy
  data:
    - secretKey: client-secret
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/dex-client-oauth2-proxy-secret
    - secretKey: cookie-secret
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/oauth2-proxy-cookie-secret
