apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: infisical-db
spec:
  instances: 2
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-system-trixie
  bootstrap:
    initdb:
      database: infisical
      owner: infisical
  storage:
    size: 5Gi
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "1"
