apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: infisical-redis
spec:
  replicas: 2
  authentication:
    passwordFromSecret:
      name: infisical-redis-auth
      key: password
  snapshot:
    cron: "*/5 * * * *"
    enableOnMasterOnly: true
    persistentVolumeClaimSpec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - dragonfly
              - key: dragonfly.dragonflydb.io/name
                operator: In
                values:
                  - infisical-redis
          topologyKey: kubernetes.io/hostname
