apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infisical-redis-auth
spec:
  refreshInterval: 1h
  target:
    name: infisical-redis-auth
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/infisical-redis-password
      sourceRef:
        storeRef:
          name: aws-ssm
          kind: ClusterSecretStore
