apiVersion: batch/v1
kind: Job
metadata:
  name: restart-argocd-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: argocd-server
      containers:
        - name: kubectl
          image: alpine/k8s:1.36.2
          imagePullPolicy: IfNotPresent
          command:
            - kubectl
            - rollout
            - restart
            - deploy/argocd-server
            - -n
            - argocd
