apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor-runtime
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: tandoor-openbao
  target:
    name: tandoor-runtime
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .secretKey }}"
        SOCIAL_PROVIDERS: allauth.socialaccount.providers.openid_connect
        SOCIALACCOUNT_PROVIDERS: >-
          {"openid_connect":{"OAUTH_PKCE_ENABLED":true,"APPS":[{"provider_id":"zitadel","name":"ZITADEL","client_id":"{{ .clientId }}","secret":"{{ .clientSecret }}","settings":{"server_url":"{{ .discoveryUrl }}"}}]}}
  data:
    - secretKey: secretKey
      remoteRef:
        key: tandoor/runtime
        property: secretKey
    - secretKey: clientId
      remoteRef:
        key: tandoor/oidc
        property: clientId
    - secretKey: clientSecret
      remoteRef:
        key: tandoor/oidc
        property: clientSecret
    - secretKey: discoveryUrl
      remoteRef:
        key: tandoor/oidc
        property: discoveryUrl
