apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tandoor-runtime
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: tandoor-openbao
  target:
    name: tandoor-runtime
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .secretKey }}"
  data:
    - secretKey: secretKey
      remoteRef:
        key: tandoor/runtime
        property: secretKey
