apiVersion: v1
kind: ServiceAccount
metadata:
  name: tandoor-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: tandoor-openbao
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider:
    vault:
      server: http://openbao-active.openbao.svc.cluster.local:8200
      path: applications
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: tandoor-secrets
          serviceAccountRef:
            name: tandoor-secrets
