apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-secrets
  namespace: dex
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: dex-secrets
  data:
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/dex-github-oauth-client-secret
    - secretKey: ARGOCD_CLIENT_SECRET
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/dex-client-argocd-secret
    - secretKey: GRAFANA_CLIENT_SECRET
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/dex-client-grafana-secret
    - secretKey: OAUTH2_PROXY_CLIENT_SECRET
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/dex-client-oauth2-proxy-secret
    - secretKey: OPENBAO_CLIENT_SECRET
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/dex-client-openbao-secret
