apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: visitor-ip-probe-tls
spec:
  secretName: visitor-ip-probe-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - visitor-ip-probe.levizitting.com
  usages:
    - digital signature
    - key encipherment
