apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: visitor-ip-probe
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingress-cloudflared.yaml
  - certificate.yaml
  - certificate-cloudflared.yaml
  - networkpolicy.yaml
