apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: sparky-server
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: sparky
      app.kubernetes.io/component: server
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: sparky
              app.kubernetes.io/component: frontend
      ports:
        - protocol: TCP
          port: 3010
