apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sparky-app-db
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshPolicy: CreatedOnce
  target:
    name: sparky-app-db
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: sparky_app
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: sparky-app-db-password
