apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: sparky-frontend
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sparky
      app.kubernetes.io/component: frontend
