- op: replace
  path: /metadata/name
  value: sparky-backup
- op: replace
  path: /spec/backend/repoPasswordSecretRef/name
  value: sparky-k8up-repo-password
- op: replace
  path: /spec/backend/b2/path
  value: sparky
- op: replace
  path: /spec/backup/schedule
  value: '15 8 * * *'
- op: replace
  path: /spec/backup/labelSelectors/0/matchLabels/backup.k8up.io~1app
  value: sparky
