apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparky-uploads
  labels:
    backup.k8up.io/app: sparky
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
