apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  url: https://argocd.levizitting.com
  admin.enabled: "true"
  oidc.tls.insecure.skip.verify: "true"
  oidc.config: |
    name: Dex
    issuer: https://sso.levizitting.com
    clientID: argocd
    clientSecret: $argocd-secret:oidc.argocd.clientSecret
    requestedScopes: ["openid", "profile", "email"]
