apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dns-gateway-auth-key
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: dns-gateway-auth-key
    creationPolicy: Owner
  data:
    - secretKey: authkey
      remoteRef:
        key: /homelab/headscale/pods/lz/dns-gateway-auth-key
