apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dex-argocd-client-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: dex-argocd-client-secret
  data:
    - secretKey: client-secret
      remoteRef:
        key: /vm-workloads/lz/infra-vm-workloads/dex-client-argocd-secret
